package seekstream

import (
	"errors"
	"io"
	"os"
)

// Buffer is the underlying buffer interface for allowing the
// non-seekable source to become seekable
type Buffer interface {
	io.ReadWriteSeeker
	Clear()
}

// TempFileBuffer Buffer implementation using temp file
// suitable for unknown or large size that does not fit inside memory
type TempFileBuffer struct {
	*os.File
}

// Clear performs cleanup on stream close
func (b *TempFileBuffer) Clear() {
	filename := b.File.Name()
	_ = b.File.Close()
	_ = os.Remove(filename)
}

// NewTempFileBuffer new temp file buffer. Using os.CreateTemp that
// creates a new temporary file in the directory dir.
// The filename is generated by taking pattern and adding a random string to the end.
func NewTempFileBuffer(dir, pattern string) (*TempFileBuffer, error) {
	file, err := os.CreateTemp(dir, pattern)
	if err != nil {
		return nil, err
	}
	return &TempFileBuffer{file}, nil
}

// MemoryBuffer Buffer implementation using memory buffer
// suitable for known size that can be fit inside memory
type MemoryBuffer struct {
	buf []byte
	i   int64 // current reading index
	s   int64 // size
}

// NewMemoryBuffer new memory buffer providing data size
func NewMemoryBuffer(size int64) *MemoryBuffer {
	return &MemoryBuffer{buf: make([]byte, size)}
}

// Read implements the io.Reader interface.
func (r *MemoryBuffer) Read(b []byte) (n int, err error) {
	if r.i >= r.s {
		return 0, io.EOF
	}
	rs := r.buf[:r.s]
	n = copy(b, rs[r.i:])
	r.i += int64(n)
	return
}

// Write implements the io.Writer interface.
func (r *MemoryBuffer) Write(p []byte) (n int, err error) {
	n = copy(r.buf[r.i:], p)
	r.s += int64(n)
	r.i += int64(n)
	return n, nil
}

// Seek implements the io.Seeker interface
func (r *MemoryBuffer) Seek(offset int64, whence int) (int64, error) {
	var abs int64
	switch whence {
	case io.SeekStart:
		abs = offset
	case io.SeekCurrent:
		abs = r.i + offset
	case io.SeekEnd:
		abs = r.s + offset
	}
	if abs < 0 {
		return 0, errors.New("invalid argument")
	}
	r.i = abs
	return abs, nil
}

// Clear performs cleanup on stream close
func (r *MemoryBuffer) Clear() {
	r.buf = nil
}
