name: coverage

on:
  workflow_run:
    workflows: ["test"]
    types: [completed]

jobs:
  upload:
    name: Upload Coverage
    runs-on: ubuntu-24.04
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./profile.cov
          fail_ci_if_error: true
